services:
  scanboxwebapi:
    image: ${DOCKER_REGISTRY-}scanboxwebapi
    container_name: scanboxwebapi
    restart: always
    build:
      context: .
      dockerfile: ScanBoxWebApi/Dockerfile
    depends_on:
      - postgres
    ports:
      - 5290:8080
      - 7290:8081
    networks:
      - mynetwork

  postgres:
    image: elestio/postgres:${SOFTWARE_VERSION_TAG}
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ADMIN_NAME}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 4778:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: elestio/pgadmin:REL-8_12
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    depends_on:
      - postgres
    ports:
      - 6917:8080
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres:
  pgadmin: